version: '3.7'
services:
  db:
    restart: always
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4306:3306"

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid &&
                      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
