# Environment variables
# - HOST_NAME
# - USER_NAME

version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "69:9b:11:e0:ad:18:21:9c:2a:87:38:3f:6c:67:27:34"

      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts

      - deploy:
          name: Start master deploy
          command: |
            sudo apt install rsync
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rsync -av --delete --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:MyWeb
            fi
