version: '2'
services:
  app:
    build: rails
    environment:
      APP_DATABASE_HOST: db
      APP_DATABASE: app_development
      APP_DATABASE_USER: root
      APP_DATABASE_PASSWORD: root
    depends_on:
      - db
      - webpacker
  db:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/Myweb
    ports:
      - "8080:8080"
  web:
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
    volumes_from:
      - app
    depends_on:
      - app
